# version: '3.8'

# services:
#   kafka:
#     image: bitnami/kafka:latest
#     ports:
#       - "9092:9092"
#       - "9094:9094"
#     environment:
#       - KAFKA_CFG_NODE_ID=0
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#       - KAFKA_KRAFT_CLUSTER_ID=L69-it6hSyuw6e_E74_Z5A
#     volumes:
#       - kafka_data:/bitnami/kafka

#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

#   payment-gateway:
#     build: 
#       context: ./services/payment-gateway
#       dockerfile: Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:9092
#       - PORT=3001
#     ports:
#       - "3001:3001"
#     depends_on:
#       - kafka
#     develop:
#       watch:
#         - action: sync
#           path: ./services/payment-gateway/src
#           target: /app/src
#         - action: rebuild
#           path: ./services/payment-gateway/package.json

#   transaction-engine:
#     build:
#       context: ./services/transaction-engine
#       dockerfile: Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:9092
#     depends_on:
#       - kafka
#     develop:
#       watch:
#         - action: sync
#           path: ./services/transaction-engine/src
#           target: /app/src
#         - action: rebuild
#           path: ./services/transaction-engine/package.json

#   notification-worker:
#     build:
#       context: ./services/notification-worker
#       dockerfile: Dockerfile
#     environment:
#       - KAFKA_BROKERS=kafka:9092
#       - PORT=3003
#     ports:
#       - "3003:3003"
#     depends_on:
#       - kafka
#     develop:
#       watch:
#         - action: sync
#           path: ./services/notification-worker/src
#           target: /app/src
#         - action: rebuild
#           path: ./services/notification-worker/package.json

#   frontend-dashboard:
#     build:
#       context: ./frontend-dashboard
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_NOTIFICATION_SERVICE_URL=http://localhost:3003
#     develop:
#       watch:
#         - action: sync
#           path: ./frontend-dashboard/src
#           target: /app/src
#         - action: rebuild
#           path: ./frontend-dashboard/package.json

# volumes:
#   kafka_data:
#   mongodb_data:
#   redis_data:

# running kafka image 
services:
  kafka:
    # UPDATED: Using the legacy repository because Bitnami removed public images
    image: bitnamilegacy/kafka:3.8
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=L69-it6hSyuw6e_E74_Z5A
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kraft
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka

volumes:
  kafka_data:
